apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: moveengines.kubemove.io
spec:
  group: kubemove.io
  names:
    kind: MoveEngine
    listKind: MoveEngineList
    plural: moveengines
    singular: moveengine
  scope: ""
  validation:
    openAPIV3Schema:
      description: MoveEngine is the Schema for the moveengines API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MoveEngineSpec defines the desired state of MoveEngine
          properties:
            includeResources:
              type: boolean
            mode:
              type: string
            movePair:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            namespace:
              type: string
            plugin:
              type: string
            pluginParameters:
              type: object
            remoteNamespace:
              type: string
            syncPeriod:
              type: string
          required:
          - includeResources
          - mode
          - movePair
          - namespace
          - plugin
          - remoteNamespace
          - syncPeriod
          type: object
        status:
          description: MoveEngineStatus defines the observed state of MoveEngine
          properties:
            DataSync:
              type: string
            DataSyncStatus:
              type: string
            LastStatus:
              type: string
            LastSyncedTime:
              format: date-time
              type: string
            Status:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            SyncedTime:
              format: date-time
              type: string
          required:
          - DataSync
          - DataSyncStatus
          - LastStatus
          - LastSyncedTime
          - Status
          - SyncedTime
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
