apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: datasyncs.kubemove.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.moveEngine
    name: MoveEngine
    type: string
  - JSONPath: .spec.mode
    name: Mode
    type: string
  - JSONPath: .status.status
    name: Status
    type: string
  - JSONPath: .status.completionTime
    name: Completion-Time
    type: date
  group: kubemove.io
  names:
    kind: DataSync
    listKind: DataSyncList
    plural: datasyncs
    singular: datasync
  scope: ""
  subresources: {}
  validation:
    openAPIV3Schema:
      description: DataSync is the Schema for the datasyncs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DataSyncSpec defines the desired state of DataSync
          properties:
            config:
              additionalProperties:
                type: string
              type: object
            mode:
              type: string
            moveEngine:
              type: string
            namespace:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            plugin:
              type: string
          required:
          - mode
          - moveEngine
          - namespace
          - plugin
          type: object
        status:
          description: DataSyncStatus defines the observed state of DataSync
          properties:
            completionTime:
              format: date-time
              type: string
            reason:
              type: string
            stage:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            status:
              type: string
          required:
          - stage
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
